export const familyData  = {
    email: null,
    people_id: 3,
    profile_picture: null,
    full_name_vn: "Lê Hùng Bá",
    birth_date: "1908-04-14",
    current_age: null,
    gender: true,
    phone_number: null,
    nationality: null,
    marital_status: true,
    death_date: "1971-02-23",
    is_alive: false,
    death_info: {
      death_date: "1971-02-23",
      is_alive: "Đã Mất",
      years_since_death: "53 năm 4 tháng",
      age_at_death: 62,
      life_span: "Hưởng Dương: 62",
    },
    children: [
      {
        email: null,
        people_id: 5,
        profile_picture: null,
        full_name_vn: "Lê Hùng Thanh",
        birth_date: "1944-09-29",
        current_age: 79,
        gender: true,
        phone_number: null,
        nationality: null,
        marital_status: true,
        death_date: null,
        is_alive: true,
        death_info: null,
        children: [
          {
            email: null,
            people_id: 12,
            profile_picture: null,
            full_name_vn: "Dung Le- David j Le",
            birth_date: "1970-09-22",
            current_age: 53,
            gender: true,
            phone_number: null,
            nationality: null,
            marital_status: true,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [
              {
                email: null,
                people_id: 18,
                profile_picture: null,
                full_name_vn: "Lê Quỳnh Nhi - Casey  Le",
                birth_date: "2008-10-12",
                current_age: 15,
                gender: false,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 19,
                profile_picture: null,
                full_name_vn: "Lê Quốc -Xavier Le",
                birth_date: "2006-12-22",
                current_age: 17,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
            ],
            spouse_name: "Trần TamLy",
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 13,
            profile_picture: null,
            full_name_vn: "Lê Vũ",
            birth_date: "1974-08-20",
            current_age: 49,
            gender: true,
            phone_number: null,
            nationality: null,
            marital_status: false,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [],
            spouse_name: null,
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 14,
            profile_picture: null,
            full_name_vn: "Lê Hiền",
            birth_date: null,
            current_age: null,
            gender: true,
            phone_number: null,
            nationality: null,
            marital_status: false,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [],
            spouse_name: null,
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 15,
            profile_picture: null,
            full_name_vn: "Lê Carol Kim",
            birth_date: "1985-12-09",
            current_age: 38,
            gender: false,
            phone_number: null,
            nationality: null,
            marital_status: false,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [],
            spouse_name: null,
            spouse_profile_picture: null,
          },
        ],
        spouse_name: "Trần Thị Trung - Mary Le",
        spouse_profile_picture: null,
      },
      {
        email: null,
        people_id: 6,
        profile_picture: null,
        full_name_vn: "Lê Thế Bích",
        birth_date: "1948-05-10",
        current_age: 76,
        gender: true,
        phone_number: null,
        nationality: null,
        marital_status: true,
        death_date: null,
        is_alive: true,
        death_info: null,
        children: [
          {
            email: null,
            people_id: 22,
            profile_picture: null,
            full_name_vn: "Lê Nguyên Hoàng Sa",
            birth_date: "1976-03-19",
            current_age: 48,
            gender: true,
            phone_number: "0978880099",
            nationality: null,
            marital_status: true,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [
              {
                email: null,
                people_id: 30,
                profile_picture: null,
                full_name_vn: "Lê Vinh",
                birth_date: "2008-05-21",
                current_age: 16,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 31,
                profile_picture: null,
                full_name_vn: "Lê Tâm",
                birth_date: "2011-05-17",
                current_age: 13,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 32,
                profile_picture: null,
                full_name_vn: "Lê Minh",
                birth_date: "2018-01-15",
                current_age: 6,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
            ],
            spouse_name: "Vũ Thuỵ Lệ Thủy",
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 23,
            profile_picture: null,
            full_name_vn: "Lê Nguyên Trường Sa",
            birth_date: "1977-08-11",
            current_age: 46,
            gender: true,
            phone_number: "090101003989",
            nationality: null,
            marital_status: false,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [
              {
                email: null,
                people_id: 35,
                profile_picture: null,
                full_name_vn: "Lê Nhân Văn",
                birth_date: null,
                current_age: null,
                gender: false,
                phone_number: "081193737370",
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
            ],
            spouse_name: null,
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 24,
            profile_picture: null,
            full_name_vn: "Lê Nguyên Châu Sa",
            birth_date: "1979-07-02",
            current_age: 45,
            gender: true,
            phone_number: "0899399799",
            nationality: null,
            marital_status: true,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [
              {
                email: null,
                people_id: 38,
                profile_picture: null,
                full_name_vn: "Lê Uyên Nhi",
                birth_date: "2005-03-02",
                current_age: 19,
                gender: false,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
            ],
            spouse_name: "Phạm Xuân Mai",
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 25,
            profile_picture: null,
            full_name_vn: "Lê Nguyên Kim Sa",
            birth_date: "1982-04-02",
            current_age: 42,
            gender: true,
            phone_number: null,
            nationality: null,
            marital_status: false,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [],
            spouse_name: null,
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 26,
            profile_picture: null,
            full_name_vn: "Lê Nguyên Sa",
            birth_date: "1984-02-04",
            current_age: 40,
            gender: true,
            phone_number: "09810780898",
            nationality: null,
            marital_status: true,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [
              {
                email: null,
                people_id: 41,
                profile_picture: null,
                full_name_vn: "Lê Nguyên Anh Vũ",
                birth_date: "2021-01-17",
                current_age: 3,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 42,
                profile_picture: null,
                full_name_vn: "Lê Nguyên Hà My",
                birth_date: "2023-09-30",
                current_age: 0,
                gender: false,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
            ],
            spouse_name: "Trần Trinh Nữ",
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 27,
            profile_picture: null,
            full_name_vn: "Lê Nguyên My Sa",
            birth_date: "1990-12-10",
            current_age: 33,
            gender: false,
            phone_number: null,
            nationality: null,
            marital_status: true,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [
              {
                email: null,
                people_id: 45,
                profile_picture: null,
                full_name_vn: "Phạm Trần Duy Anh",
                birth_date: "2017-07-24",
                current_age: 6,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 46,
                profile_picture: null,
                full_name_vn: "Phạm Trần Gia Anh",
                birth_date: "2023-01-18",
                current_age: 1,
                gender: false,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
            ],
            spouse_name: "Phạm Trần Xuân Triệu",
            spouse_profile_picture: null,
          },
        ],
        spouse_name: "Nguyễn Thị Thanh",
        spouse_profile_picture: null,
      },
      {
        email: null,
        people_id: 7,
        profile_picture: null,
        full_name_vn: "Lê Minh Cầm",
        birth_date: "1953-12-10",
        current_age: 70,
        gender: false,
        phone_number: null,
        nationality: null,
        marital_status: true,
        death_date: null,
        is_alive: true,
        death_info: null,
        children: [
          {
            email: null,
            people_id: 49,
            profile_picture: null,
            full_name_vn: "Lưu Đức Duy",
            birth_date: "1973-05-04",
            current_age: 51,
            gender: true,
            phone_number: "0931384939",
            nationality: null,
            marital_status: true,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [
              {
                email: null,
                people_id: 60,
                profile_picture: null,
                full_name_vn: "Lưu Gia Huy",
                birth_date: "1998-03-20",
                current_age: 26,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 61,
                profile_picture: null,
                full_name_vn: "Lưu Gia Hân",
                birth_date: "2002-03-08",
                current_age: 22,
                gender: false,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 62,
                profile_picture: null,
                full_name_vn: "Lưu Gia Hiếu",
                birth_date: "2004-06-17",
                current_age: 20,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 63,
                profile_picture: null,
                full_name_vn: "Lưu Gia Hoàng",
                birth_date: "2012-10-01",
                current_age: 11,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 64,
                profile_picture: null,
                full_name_vn: "Lưu Gia Khánh Hà",
                birth_date: "2019-01-01",
                current_age: 5,
                gender: false,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
            ],
            spouse_name: "Bùi Thùy Linh",
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 50,
            profile_picture: null,
            full_name_vn: "Lưu Duy Linh",
            birth_date: "1975-03-18",
            current_age: 49,
            gender: true,
            phone_number: "0903741948",
            nationality: null,
            marital_status: true,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [
              {
                email: null,
                people_id: 67,
                profile_picture: null,
                full_name_vn: "Lưu Hoàng Thảo Nhi",
                birth_date: "2007-04-18",
                current_age: 17,
                gender: false,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 68,
                profile_picture: null,
                full_name_vn: "Lưu Hoàng Bảo Ngọc",
                birth_date: "2012-07-19",
                current_age: 11,
                gender: false,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
            ],
            spouse_name: "Hoàng Thụy Phương Linh",
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 51,
            profile_picture: null,
            full_name_vn: "Lưu Thùy Linh Giang",
            birth_date: "1977-04-16",
            current_age: 47,
            gender: false,
            phone_number: "0973170353",
            nationality: null,
            marital_status: true,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [
              {
                email: null,
                people_id: 71,
                profile_picture: null,
                full_name_vn: "Nguyễn Thảo Vy",
                birth_date: "2000-02-10",
                current_age: 24,
                gender: false,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 72,
                profile_picture: null,
                full_name_vn: "Nguyễn Mạnh Tường",
                birth_date: "2002-09-21",
                current_age: 21,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 73,
                profile_picture: null,
                full_name_vn: "Nguyễn Minh Quân",
                birth_date: "2005-01-10",
                current_age: 19,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 74,
                profile_picture: null,
                full_name_vn: "Nguyễn Tiến Minh",
                birth_date: "2015-05-23",
                current_age: 9,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
            ],
            spouse_name: "Nguyễn Đức Thường",
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 52,
            profile_picture: null,
            full_name_vn: "Lưu Lam Sơn",
            birth_date: "1980-06-22",
            current_age: 44,
            gender: true,
            phone_number: "0775123945",
            nationality: null,
            marital_status: true,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [
              {
                email: null,
                people_id: 77,
                profile_picture: null,
                full_name_vn: "Lưu Hà Minh Tâm",
                birth_date: "2011-11-28",
                current_age: 12,
                gender: false,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 78,
                profile_picture: null,
                full_name_vn: "Lưu Hà Minh Châu",
                birth_date: "2015-10-20",
                current_age: 8,
                gender: false,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
            ],
            spouse_name: "Hà Thị Bích Phương",
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 53,
            profile_picture: null,
            full_name_vn: "Lưu Sơn Đông",
            birth_date: "1982-05-25",
            current_age: 42,
            gender: true,
            phone_number: "0981817017",
            nationality: null,
            marital_status: true,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [
              {
                email: null,
                people_id: 81,
                profile_picture: null,
                full_name_vn: "Lưu Thông Y",
                birth_date: "2017-08-09",
                current_age: 6,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
            ],
            spouse_name: "Nguyễn Thị Minh Hậu",
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 54,
            profile_picture: null,
            full_name_vn: "Lưu Thùy Đông Phương",
            birth_date: "1983-10-01",
            current_age: 40,
            gender: false,
            phone_number: "0834139739",
            nationality: null,
            marital_status: true,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [
              {
                email: null,
                people_id: 84,
                profile_picture: null,
                full_name_vn: "Vũ Thùy Chi",
                birth_date: "2010-09-25",
                current_age: 13,
                gender: false,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 85,
                profile_picture: null,
                full_name_vn: "Vũ Hoàng Long",
                birth_date: "2012-04-15",
                current_age: 12,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
            ],
            spouse_name: "Vũ Trần Huy Quang",
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 55,
            profile_picture: null,
            full_name_vn: "Lưu Phương Dung",
            birth_date: "1986-05-20",
            current_age: null,
            gender: false,
            phone_number: null,
            nationality: null,
            marital_status: true,
            death_date: "2021-10-14",
            is_alive: false,
            death_info: {
              death_date: "2021-10-14",
              is_alive: "Đã Mất",
              years_since_death: "2 năm 8 tháng",
              age_at_death: 35,
              life_span: "Hưởng Dương: 35",
            },
            children: [
              {
                email: null,
                people_id: 88,
                profile_picture: null,
                full_name_vn: "Bùi Hoàng Bách",
                birth_date: "2016-04-15",
                current_age: 8,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
              {
                email: null,
                people_id: 89,
                profile_picture: null,
                full_name_vn: "Bùi Hoàng Thiên",
                birth_date: "2019-05-31",
                current_age: 5,
                gender: true,
                phone_number: null,
                nationality: null,
                marital_status: false,
                death_date: null,
                is_alive: true,
                death_info: null,
                children: [],
                spouse_name: null,
                spouse_profile_picture: null,
              },
            ],
            spouse_name: "Bùi Viết Trình",
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 56,
            profile_picture: null,
            full_name_vn: "Lưu Dũng Anh",
            birth_date: "1989-05-29",
            current_age: 35,
            gender: true,
            phone_number: null,
            nationality: null,
            marital_status: false,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [],
            spouse_name: null,
            spouse_profile_picture: null,
          },
          {
            email: null,
            people_id: 57,
            profile_picture: null,
            full_name_vn: "Lưu Thùy Anh Đức",
            birth_date: "1991-08-26",
            current_age: 32,
            gender: true,
            phone_number: "0914683133",
            nationality: null,
            marital_status: true,
            death_date: null,
            is_alive: true,
            death_info: null,
            children: [],
            spouse_name: null,
            spouse_profile_picture: null,
          },
        ],
        spouse_name: "Lưu Quang Diệm",
        spouse_profile_picture: null,
      },
      {
        email: null,
        people_id: 8,
        profile_picture: null,
        full_name_vn: "Lê Minh Vân",
        birth_date: "1958-12-10",
        current_age: 65,
        gender: false,
        phone_number: null,
        nationality: null,
        marital_status: false,
        death_date: null,
        is_alive: true,
        death_info: null,
        children: [],
        spouse_name: null,
        spouse_profile_picture: null,
      },
      {
        email: null,
        people_id: 9,
        profile_picture: null,
        full_name_vn: "Lê Minh Nguyệt",
        birth_date: "1956-08-11",
        current_age: null,
        gender: false,
        phone_number: null,
        nationality: null,
        marital_status: false,
        death_date: "1976-03-24",
        is_alive: false,
        death_info: {
          death_date: "1976-03-24",
          is_alive: "Đã Mất",
          years_since_death: "48 năm 3 tháng",
          age_at_death: 19,
          life_span: "Hưởng Dương: 19",
        },
        children: [],
        spouse_name: null,
        spouse_profile_picture: null,
      },
    ],
    spouse_name: "Nguyễn Thị Minh",
    spouse_profile_picture: null,
  }; // Paste your JSON data here